# Generated by Django 3.1 on 2021-09-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='time',
            field=models.TimeField(),
        ),
    ]
