# Generated by Django 3.1 on 2021-09-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0003_auto_20210912_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylist',
            old_name='compelte',
            new_name='complete',
        ),
    ]
