# Generated by Django 3.1 on 2021-09-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0004_auto_20210912_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='important',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
