# Generated by Django 3.1 on 2021-10-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0005_auto_20210914_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='date',
            field=models.DateField(),
        ),
    ]
