# Generated by Django 3.1 on 2021-10-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0006_auto_20211015_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
