# Generated by Django 3.1 on 2021-10-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0007_auto_20211020_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
