# Generated by Django 3.1 on 2021-11-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0009_attachmentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylist',
            name='done_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='mylist',
            name='done_user',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mylist',
            name='file_path',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mylist',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AttachmentFile',
        ),
    ]
