# Generated by Django 3.1 on 2021-11-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0010_auto_20211108_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.IntegerField(null=True)),
                ('file_path', models.CharField(max_length=50, null=True)),
                ('done_user', models.CharField(max_length=20, null=True)),
                ('start_time', models.TimeField(null=True)),
                ('done_time', models.TimeField(null=True)),
            ],
            options={
                'db_table': 'AttachmentFile',
            },
        ),
        migrations.RemoveField(
            model_name='mylist',
            name='done_time',
        ),
        migrations.RemoveField(
            model_name='mylist',
            name='done_user',
        ),
        migrations.RemoveField(
            model_name='mylist',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='mylist',
            name='start_time',
        ),
    ]
