# Generated by Django 3.1 on 2021-12-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0013_auto_20211109_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylist',
            name='time',
        ),
        migrations.AddField(
            model_name='mylist',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
